# -*- coding: utf-8 -*-
"""Demo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xdXeFBEIOCrHUJ3Rof2kgNwPRaoCHQzG
"""

def sum(a,b):
    return a+b

def sub(a,b):
    return a-b

def mul(a,b):
    return a*b

def div(a,b):
    return a/b

a = int(input("Enter a number: "))
b = int(input("Enter a number: "))

print(sum(a,b))
print(sub(a,b))
print(mul(a,b))
print(div(a,b))