# -*- coding: utf-8 -*-
"""Demo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xdXeFBEIOCrHUJ3Rof2kgNwPRaoCHQzG
"""

def sum(a,b):
    return a+b

def sub(a,b):
    return a-b

def mul(a,b):
    return a*b

def div(a,b):
    return a/b

x = int(input("Enter a number: "))
y = int(input("Enter a number: "))

print(sum(x,y))
print(sub(x,y))
print(mul(x,y))
print(div(x,y))
